### ISSUE TITLE
Split Reference.accession into accession and version

### ISSUE THREAD

**Issue by martijnvermaat** [mutalyzer/mutalyzer#399]
It's a bit annoying that the optional version number is included in the `Reference.accession` column. For one, it makes querying by just accession (without version) hard.

Plan of action for migration:

- [x] Add `Reference.version` column. #400
- [x] Update codebase to write versions to `Reference.version` (in addition to `Reference.accession`). #400
- [ ] Release.
- [ ] Populate `Reference.version` using `Reference.accession`. #401
- [ ] Add unique index on `Reference.accession` and `Reference.version`. #401
- [ ] Drop unique index on `Reference.accession`. #401
- [ ] Update codebase to read from `Reference.version` and ignore potential versions in `Reference.accession`. #401
- [ ] Update codebase to not write versions to `Reference.accession`.
- [ ] Release.
- [ ] Remove versions from `Reference.accession`.
- [ ] Update codebase to remove ignoring potential versions in `Reference.accession`.

**Comment by martijnvermaat** [comment]
While working on this, I came to the conclusion it's not a good idea to split accession and version. It introduces a lot of complexity for little benefit.

In general, Mutalyzer always sees 'accession.version' as the identifier of the reference and because we always want exact identifiers, there is little need for accession numbers without version.

The most obvious use case I see for a split is that we can easily query available references with a certain accession, not taking version into account, as a way to inform the user when a specific reference identifier was not found. But I guess we better have this use case as the exception, and make our life easier for the rest.

So I guess I'm aborting this for now. Addition of the `version` column has already landed in the master branch, but this is easy to roll back. The original column has not yet been touched in master.

**Comment by martijnvermaat** [comment]
Reverted in #402
